# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
python:
  - 3.6
  - 3.7
install:
  - pip install -r requirements/dev.txt
  - nvm install 12
  - nvm use 12
  - npm install
before_script:
  - cp .env.example .env
  - npm run lint
  - flask lint --check
script: flask test
